language: cpp 
dist: trusty 
sudo: required 
env: 
 matrix: 
  - PACKAGE='CHECK' 
  - PACKAGE='AABB_tree Advancing_front_surface_reconstruction Algebraic_foundations ' 
  - PACKAGE='Algebraic_kernel_d Algebraic_kernel_for_circles Algebraic_kernel_for_spheres ' 
  - PACKAGE='Alpha_shapes_2 Alpha_shapes_3 Apollonius_graph_2 ' 
  - PACKAGE='Arithmetic_kernel Arrangement_on_surface_2 Barycentric_coordinates_2 ' 
  - PACKAGE='BGL Boolean_set_operations_2 Bounding_volumes ' 
  - PACKAGE='Box_intersection_d Cartesian_kernel CGAL_Core ' 
  - PACKAGE='CGAL_ImageIO CGAL_ipelets Circular_kernel_2 ' 
  - PACKAGE='Circular_kernel_3 Circulator Combinatorial_map ' 
  - PACKAGE='Cone_spanners_2 Convex_decomposition_3 Convex_hull_2 ' 
  - PACKAGE='Convex_hull_3 Convex_hull_d Distance_2 ' 
  - PACKAGE='Distance_3 Envelope_2 Envelope_3 ' 
  - PACKAGE='Filtered_kernel Generalized_map Generator ' 
  - PACKAGE='Geomview GraphicsView HalfedgeDS ' 
  - PACKAGE='Hash_map Homogeneous_kernel Inscribed_areas ' 
  - PACKAGE='Installation Interpolation Intersections_2 ' 
  - PACKAGE='Intersections_3 Interval_skip_list Interval_support ' 
  - PACKAGE='Inventor Jet_fitting_3 Kernel_23 ' 
  - PACKAGE='Kernel_d Kinetic_data_structures Kinetic_framework ' 
  - PACKAGE='LEDA Linear_cell_complex MacOSX ' 
  - PACKAGE='Maintenance Matrix_search Mesh_2 ' 
  - PACKAGE='Mesh_3 Mesher_level Minkowski_sum_2 ' 
  - PACKAGE='Minkowski_sum_3 Modifier Modular_arithmetic ' 
  - PACKAGE='Nef_2 Nef_3 Nef_S2 ' 
  - PACKAGE='NewKernel_d Number_types OpenNL ' 
  - PACKAGE='Operations_on_polyhedra Optimal_transportation_reconstruction_2 Optimisation_basic ' 
  - PACKAGE='Partition_2 Periodic_2_triangulation_2 Periodic_3_triangulation_3 ' 
  - PACKAGE='Point_set_2 Point_set_3 Point_set_processing_3 ' 
  - PACKAGE='Point_set_shape_detection_3 Poisson_surface_reconstruction_3 Polygon ' 
  - PACKAGE='Polygon_mesh_processing Polyhedron Polyhedron_IO ' 
  - PACKAGE='Polyline_simplification_2 Polynomial Polytope_distance_d ' 
  - PACKAGE='Principal_component_analysis Principal_component_analysis_LGPL Profiling_tools ' 
  - PACKAGE='Property_map QP_solver Random_numbers ' 
  - PACKAGE='Ridges_3 Scale_space_reconstruction_3 Scripts ' 
  - PACKAGE='SearchStructures Segment_Delaunay_graph_2 Segment_Delaunay_graph_Linf_2 ' 
  - PACKAGE='Skin_surface_3 Snap_rounding_2 Solver_interface ' 
  - PACKAGE='Spatial_searching Spatial_sorting STL_Extension ' 
  - PACKAGE='Straight_skeleton_2 Stream_lines_2 Stream_support ' 
  - PACKAGE='Subdivision_method_3 Surface_mesh Surface_mesh_deformation ' 
  - PACKAGE='Surface_mesher Surface_mesh_parameterization Surface_mesh_segmentation ' 
  - PACKAGE='Surface_mesh_shortest_path Surface_mesh_simplification Surface_mesh_skeletonization ' 
  - PACKAGE='Sweep_line_2 TDS_2 TDS_3 ' 
  - PACKAGE='Testsuite Three Triangulation ' 
  - PACKAGE='Triangulation_2 Triangulation_3 Union_find ' 
  - PACKAGE='Visibility_2 Voronoi_diagram_2 wininst ' 
  - PACKAGE='Polyhedron_demo' 
compiler: 
  - clang-3.6
  - gcc  
install: 
  - if [[ "$CXX" = "clang++" ]]; then export CXX=clang++-3.6 CC=clang-3.6; fi
before_script: 
- mkdir -p build 
- cd build 
- cmake -DCGAL_HEADER_ONLY=ON -DQt5_DIR="/opt/qt55/lib/cmake/Qt5" -DQt5Svg_DIR="/opt/qt55/lib/cmake/Qt5Svg" -DQt5OpenGL_DIR="/opt/qt55/lib/cmake/Qt5OpenGL" -DWITH_demos:BOOL=TRUE -DWITH_examples:BOOL=true -DWITH_tests:BOOL=TRUE -DCMAKE_CXX_FLAGS_RELEASE=-DCGAL_NDEBUG .. 
- make 
- cd .. 
script: 
- cd ./.travis
- bash -x -e ./build_package.sh $PACKAGE
addons: 
  apt:
    sources:
      - sourceline: 'ppa:ppsspp/cmake' 
      - sourceline: 'ppa:hedges/qt5.5'
    packages:
      - clang-3.6
      - zsh
      - cmake 
      - libboost1.55-dev 
      - libboost-system1.55-dev 
      - libboost-program-options1.55-dev 
      - libboost-thread1.55-dev 
      - libgmp-dev 
      - libmpfr-dev 
      - zlib1g-dev 
      - libeigen3-dev # too old 
      - qt55base
      - qt55script 
      - qt55svg
      - qt55tools
      - qt55graphicaleffects
       
      - mesa-common-dev
      - libglu1-mesa-dev
      # Not allowed (yet) 
      # - geomview 
      # - libglew1.5-dev 
      # - libipe-dev 
      # - libmpfi-dev 
notifications:
  email:
    on_success: change # default: always
    on_failure: always # default: always
