#ifndef SCENE_STARSET3_ITEM_CONFIG_H
#define SCENE_STARSET3_ITEM_CONFIG_H

#ifdef scene_starset3_item_EXPORTS
#  define SCENE_STARSET3_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_STARSET3_ITEM_EXPORT Q_DECL_IMPORT
#endif


#define USE_AABB_TREE_OF_BBOXES  1

#endif // SCENE_STARSET3_ITEM_CONFIG_H
