#ifndef SCENE_CONSTRAINED_SURFACE_IMPLICIT_ITEM_CONFIG_H
#define SCENE_CONSTRAINED_SURFACE_IMPLICIT_ITEM_CONFIG_H

#ifdef scene_constrained_surface_implicit_item_EXPORTS
#  define SCENE_CONSTRAINED_SURFACE_IMPLICIT_ITEM_EXPORT Q_DECL_EXPORT
#else
#  define SCENE_CONSTRAINED_SURFACE_IMPLICIT_ITEM_EXPORT Q_DECL_IMPORT
#endif

#endif // SCENE_CONSTRAINED_SURFACE_IMPLICIT_ITEM_CONFIG_H
